config/routes.rb
Rails.application.routes.draw do
  resources :pokemon_types
  resources :pokemons
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  before_action :set_pokemon_type, only: %i[ show edit update destroy ]

  # GET /pokemon_types or /pokemon_types.json
  def index
    @pokemon_types = PokemonType.all
  end

  # GET /pokemon_types/1 or /pokemon_types/1.json
  def show
  end

  # GET /pokemon_types/new
  def new
    @pokemon_type = PokemonType.new
  end

  # GET /pokemon_types/1/edit
  def edit
  end

  # POST /pokemon_types or /pokemon_types.json
  def create
    @pokemon_type = PokemonType.new(pokemon_type_params)

    respond_to do |format|
      if @pokemon_type.save
        format.html { redirect_to @pokemon_type, notice: "Pokemon type was successfully created." }
        format.json { render :show, status: :created, location: @pokemon_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_types/1 or /pokemon_types/1.json
  def update
    respond_to do |format|
      if @pokemon_type.update(pokemon_type_params)
        format.html { redirect_to @pokemon_type, notice: "Pokemon type was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_types/1 or /pokemon_types/1.json
  def destroy
    @pokemon_type.destroy
    respond_to do |format|
      format.html { redirect_to pokemon_types_url, notice: "Pokemon type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_type
      @pokemon_type = PokemonType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_type_params
      params.require(:pokemon_type).permit(:nomType)
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: %i[ show edit update destroy ]

  # GET /pokemons or /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1 or /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons or /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully created." }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1 or /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: "Pokemon was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1 or /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: "Pokemon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_params
      params.require(:pokemon).permit(:numero, :nom, :hp, :attack, :defense, :speAttack, :speDefense, :vitesse, :total)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorProjetPokemon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemon_types/_form.html.erb
<%= form_with(model: pokemon_type) do |form| %>
  <% if pokemon_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon_type.errors.count, "error") %> prohibited this pokemon_type from being saved:</h2>

      <ul>
        <% pokemon_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nomType %>
    <%= form.text_field :nomType %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon_types/edit.html.erb
<h1>Editing Pokemon Type</h1>

<%= render 'form', pokemon_type: @pokemon_type %>

<%= link_to 'Show', @pokemon_type %> |
<%= link_to 'Back', pokemon_types_path %>

app/views/pokemon_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemon Types</h1>

<table>
  <thead>
    <tr>
      <th>Nomtype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon_types.each do |pokemon_type| %>
      <tr>
        <td><%= pokemon_type.nomType %></td>
        <td><%= link_to 'Show', pokemon_type %></td>
        <td><%= link_to 'Edit', edit_pokemon_type_path(pokemon_type) %></td>
        <td><%= link_to 'Destroy', pokemon_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon Type', new_pokemon_type_path %>

app/views/pokemon_types/new.html.erb
<h1>New Pokemon Type</h1>

<%= render 'form', pokemon_type: @pokemon_type %>

<%= link_to 'Back', pokemon_types_path %>

app/views/pokemon_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nomtype:</strong>
  <%= @pokemon_type.nomType %>
</p>

<%= link_to 'Edit', edit_pokemon_type_path(@pokemon_type) %> |
<%= link_to 'Back', pokemon_types_path %>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
        <% pokemon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero %>
    <%= form.number_field :numero %>
  </div>

  <div class="field">
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </div>

  <div class="field">
    <%= form.label :hp %>
    <%= form.number_field :hp %>
  </div>

  <div class="field">
    <%= form.label :attack %>
    <%= form.number_field :attack %>
  </div>

  <div class="field">
    <%= form.label :defense %>
    <%= form.number_field :defense %>
  </div>

  <div class="field">
    <%= form.label :speAttack %>
    <%= form.number_field :speAttack %>
  </div>

  <div class="field">
    <%= form.label :speDefense %>
    <%= form.number_field :speDefense %>
  </div>

  <div class="field">
    <%= form.label :vitesse %>
    <%= form.number_field :vitesse %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.number_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Numero</th>
      <th>Nom</th>
      <th>Hp</th>
      <th>Attack</th>
      <th>Defense</th>
      <th>Speattack</th>
      <th>Spedefense</th>
      <th>Vitesse</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.numero %></td>
        <td><%= pokemon.nom %></td>
        <td><%= pokemon.hp %></td>
        <td><%= pokemon.attack %></td>
        <td><%= pokemon.defense %></td>
        <td><%= pokemon.speAttack %></td>
        <td><%= pokemon.speDefense %></td>
        <td><%= pokemon.vitesse %></td>
        <td><%= pokemon.total %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero:</strong>
  <%= @pokemon.numero %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @pokemon.nom %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @pokemon.hp %>
</p>

<p>
  <strong>Attack:</strong>
  <%= @pokemon.attack %>
</p>

<p>
  <strong>Defense:</strong>
  <%= @pokemon.defense %>
</p>

<p>
  <strong>Speattack:</strong>
  <%= @pokemon.speAttack %>
</p>

<p>
  <strong>Spedefense:</strong>
  <%= @pokemon.speDefense %>
</p>

<p>
  <strong>Vitesse:</strong>
  <%= @pokemon.vitesse %>
</p>

<p>
  <strong>Total:</strong>
  <%= @pokemon.total %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>